/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

import Connection.Connect;
import DAO.LOPHOCPHANDAO;
import Model.LopHP;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Acer
 */
public class LOPHOCPHAN extends javax.swing.JFrame {

    /**
     * Creates new form LOPHOCPHAN
     */
    DefaultTableModel tbtModel;
    public LOPHOCPHAN() {
        initComponents();
        setLocationRelativeTo(null);
        initcbbMaGV();
        initcbbMaHP();
        Loadulieu();
    }
     private void initcbbMaHP() {
        try {
            String sql = "Select MaHP from HocPhan";
            Connection conn = Connect.openConnect();
            PreparedStatement pm = conn.prepareStatement(sql);
            ResultSet rs = pm.executeQuery();
            cbbMaHP.removeAllItems();
            while (rs.next()) {
                cbbMaHP.addItem(rs.getString("MaHP"));
            }
            rs.close();
            pm.close();
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
    }
    
    private void initcbbMaGV() {
        try {
            String sql = "Select MaGV from GiangVien";
            Connection conn = Connect.openConnect();
            PreparedStatement pm = conn.prepareStatement(sql);
            ResultSet rs = pm.executeQuery();
            cbbMaGV.removeAllItems();
            while (rs.next()) {
                cbbMaGV.addItem(rs.getString("MaGV"));
            }
            rs.close();
            pm.close();
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
    }
     public void Loadulieu() {

        try {
            tbl_lophp.removeAll();
            String[] arr = {"Mã lớp học phần HP", "Tên học phần", "Ngày bắt đầu","Ngày kết thúc","Ngày dự kiến thi","Học kỳ","Năm","Mã HP","Mã GV"};
            tbtModel = new DefaultTableModel(arr, 0);
            String sql = "SELECT * FROM LopHP";
            Connection conn = Connect.openConnect();
            PreparedStatement pm = conn.prepareStatement(sql);
            ResultSet rs = pm.executeQuery();
            tbtModel.setRowCount(0);
            while (rs.next()) {
                String[] row = new String[]
            {
                    rs.getString("MaLHP"),        rs.getString("TenHP"),
                    rs.getString("NgayBd"),       rs.getString("NgayKt"),
                    rs.getString("NgayDukienthi"),rs.getString("HK"),
                    rs.getString("Nam"),          rs.getString("MaHP"),
                    rs.getString("MaGV")
                };
                
                tbtModel.addRow(row);
            }
            tbl_lophp.setModel(tbtModel);
            tbtModel.fireTableDataChanged();
            Connect.CloseConnect(conn);
        } catch (Exception e) {
           e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btt_trove = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtMaLHP = new javax.swing.JTextField();
        btnSua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        txtTenHP = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        lblDong6 = new javax.swing.JLabel();
        lblDong2 = new javax.swing.JLabel();
        lblDong3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_lophp = new javax.swing.JTable();
        lblDong7 = new javax.swing.JLabel();
        lblDong8 = new javax.swing.JLabel();
        lblDong9 = new javax.swing.JLabel();
        lblDong10 = new javax.swing.JLabel();
        lblDong11 = new javax.swing.JLabel();
        lblDong12 = new javax.swing.JLabel();
        txtNam = new javax.swing.JTextField();
        txtNgayBd = new javax.swing.JTextField();
        txtNgayDukienthi = new javax.swing.JTextField();
        txtNgayKt = new javax.swing.JTextField();
        cbbHK = new javax.swing.JComboBox<>();
        cbbMaGV = new javax.swing.JComboBox<>();
        btt_thoat1 = new javax.swing.JButton();
        cbbMaHP = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý lớp học phần");

        btt_trove.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btt_trove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/back.png"))); // NOI18N
        btt_trove.setText("Trở về");
        btt_trove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_troveActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("#9Slide03 SFU DIN Mittelschrift", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/lophp.png"))); // NOI18N
        jLabel1.setText("QUẢN LÝ LỚP HỌC PHẦN");

        txtMaLHP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMaLHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaLHPActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/sua.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnxoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/xoa.png"))); // NOI18N
        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        txtTenHP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/them.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        lblDong6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDong6.setText("Năm:");

        lblDong2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDong2.setText("Mã lớp học phần:");

        lblDong3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDong3.setText("Tên lớp HP:");

        tbl_lophp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_lophp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", "", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(tbl_lophp);

        lblDong7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDong7.setText("Ngày dự kiến thi:");

        lblDong8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDong8.setText("Ngày kết thúc:");

        lblDong9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDong9.setText("Ngày bắt đầu:");

        lblDong10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDong10.setText("Mã học phần:");

        lblDong11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDong11.setText("Học kỳ:");

        lblDong12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDong12.setText("Mã giảng viên:");

        txtNam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtNgayBd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtNgayDukienthi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtNgayKt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        cbbHK.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbbHK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        cbbMaGV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btt_thoat1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btt_thoat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/thoat.png"))); // NOI18N
        btt_thoat1.setText("Thoát");
        btt_thoat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_thoat1ActionPerformed(evt);
            }
        });

        cbbMaHP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(btnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btt_trove, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDong2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDong10, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbbMaHP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(88, 88, 88))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDong7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDong8, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDong9, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNgayDukienthi))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNgayBd)
                                            .addComponent(txtNgayKt)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtMaLHP, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))))))
                        .addGap(27, 27, 27)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDong3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenHP, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDong11, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDong6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDong12, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cbbHK, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(114, 114, 114))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNam, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                    .addComponent(cbbMaGV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 47, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btt_thoat1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(349, 349, 349))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDong2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDong3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaLHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDong9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNgayBd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTenHP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDong8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNgayKt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDong11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbbHK, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDong6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNgayDukienthi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDong7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDong10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDong12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbMaGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbMaHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnxoa)
                    .addComponent(btt_trove))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btt_thoat1)
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btt_troveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_troveActionPerformed
        // TODO add your handling code here:
        TRANGCHU tc = new TRANGCHU();
        tc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btt_troveActionPerformed

    private void txtMaLHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaLHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaLHPActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        if (txtMaLHP.getText().equals(""))
        {
            sb.append("MaLHP đang trống!\n");
            txtMaLHP.requestFocus();
        }
        if (sb.length() > 0)
        {
            JOptionPane.showMessageDialog(this, sb.toString(), "Cảnh báo", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try
        {
            LopHP lhp = new LopHP();
            LOPHOCPHANDAO LopHPup = new LOPHOCPHANDAO();

            lhp.setMaLHP(txtMaLHP.getText());
            lhp.setTenHP((txtTenHP.getText()));
            lhp.setNgayBd(txtNgayBd.getText());
            lhp.setNgayKt(txtNgayKt.getText());
            lhp.setNgayDukienthi((txtNgayDukienthi.getText()));
            String n = cbbHK.getItemAt(cbbHK.getSelectedIndex());
                    lhp.setHK(n);
            lhp.setNam(txtNam.getText());
            String n2 = cbbMaHP.getItemAt(cbbMaHP.getSelectedIndex());
            lhp.setMaHP(n2);
            String n1 = cbbMaGV.getItemAt(cbbMaGV.getSelectedIndex());
            lhp.setMaGV(n1);

            LopHPup.Update(lhp);
            Loadulieu();
            JOptionPane.showMessageDialog(this, "Cập nhật thông tin thành công!");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Cập nhật không thành công!");
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        if (txtMaLHP.getText().equals("")) {
            sb.append("MaLHP đang trống!\n");
        }
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb.toString(), "Cảnh báo!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int lhp = JOptionPane.showConfirmDialog(this, "Bạn muốn xóa lớp học phần này", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (lhp == JOptionPane.YES_OPTION) {
            try {
                LOPHOCPHANDAO lhpd = new LOPHOCPHANDAO();
                if (lhpd.Delete(txtMaLHP.getText())) {
                    JOptionPane.showMessageDialog(this, "Xóa lớp học phần thành công");
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa lớp học phần thất bại");
                }
                Loadulieu();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        if (txtMaLHP.getText().equals(""))
        {
            sb.append("MaLHP đang trống!\n");
            txtMaLHP.requestFocus();
        }
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb.toString(), "Cảnh báo", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            LopHP lhp = new LopHP();
            LOPHOCPHANDAO lhpd = new LOPHOCPHANDAO();

            lhp.setMaLHP(txtMaLHP.getText());
            lhp.setTenHP((txtTenHP.getText()));
            lhp.setNgayBd(txtNgayBd.getText());
            lhp.setNgayKt(txtNgayKt.getText());
            lhp.setNgayDukienthi((txtNgayDukienthi.getText()));
            String n = cbbHK.getItemAt(cbbHK.getSelectedIndex());
                    lhp.setHK(n);
            lhp.setNam(txtNam.getText());
            String n2 = cbbMaHP.getItemAt(cbbMaHP.getSelectedIndex());
            lhp.setMaHP(n2);
            String n1 = cbbMaGV.getItemAt(cbbMaGV.getSelectedIndex());
            lhp.setMaGV(n1);

            lhpd.insert(lhp);
            Loadulieu();
            JOptionPane.showMessageDialog(this, "Thêm lớp học phần thành công!");

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, "Không thể thêm lớp học phần!");
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btt_thoat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_thoat1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btt_thoat1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOPHOCPHAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOPHOCPHAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOPHOCPHAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOPHOCPHAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOPHOCPHAN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnxoa;
    private javax.swing.JButton btt_thoat1;
    private javax.swing.JButton btt_trove;
    private javax.swing.JComboBox<String> cbbHK;
    private javax.swing.JComboBox<String> cbbMaGV;
    private javax.swing.JComboBox<String> cbbMaHP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDong10;
    private javax.swing.JLabel lblDong11;
    private javax.swing.JLabel lblDong12;
    private javax.swing.JLabel lblDong2;
    private javax.swing.JLabel lblDong3;
    private javax.swing.JLabel lblDong6;
    private javax.swing.JLabel lblDong7;
    private javax.swing.JLabel lblDong8;
    private javax.swing.JLabel lblDong9;
    private javax.swing.JTable tbl_lophp;
    private javax.swing.JTextField txtMaLHP;
    private javax.swing.JTextField txtNam;
    private javax.swing.JTextField txtNgayBd;
    private javax.swing.JTextField txtNgayDukienthi;
    private javax.swing.JTextField txtNgayKt;
    private javax.swing.JTextField txtTenHP;
    // End of variables declaration//GEN-END:variables
}
